<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-17T19:28:15 IST" name="Default suite" finished-at="2023-11-17T19:28:15 IST" duration-ms="41">
    <groups>
    </groups>
    <test started-at="2023-11-17T19:28:15 IST" name="Default test" finished-at="2023-11-17T19:28:15 IST" duration-ms="41">
      <class name="com.GroupingIgnoreDepOnmethods.ValidationVerification">
        <test-method is-config="true" signature="BrowserLaunch()[pri:0, instance:com.GroupingIgnoreDepOnmethods.ValidationVerification@306e95ec]" started-at="2023-11-17T19:28:00 IST" name="BrowserLaunch" finished-at="2023-11-17T19:28:15 IST" duration-ms="15355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserLaunch -->
        <test-method signature="InputValuesListen()[pri:0, instance:com.GroupingIgnoreDepOnmethods.ValidationVerification@306e95ec]" started-at="2023-11-17T19:28:15 IST" name="InputValuesListen" finished-at="2023-11-17T19:28:15 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "String.length()" because the return value of "org.testng.ITestResult.getTestName()" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "org.testng.ITestResult.getTestName()" is null
at com.BaseMethods.ListnersClass.onTestStart(ListnersClass.java:12)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:103)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:569)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InputValuesListen -->
        <test-method is-config="true" signature="validation()[pri:0, instance:com.GroupingIgnoreDepOnmethods.ValidationVerification@306e95ec]" started-at="2023-11-17T19:28:15 IST" name="validation" finished-at="2023-11-17T19:28:21 IST" duration-ms="6062" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validation -->
      </class> <!-- com.GroupingIgnoreDepOnmethods.ValidationVerification -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
